paxos

diff --git a/bin/go b/bin/go
--- a/bin/go
+++ b/bin/go
@@ -1,4 +1,11 @@
 # 创建一个新的博客文件，按照 yyyy-mm-dd-title.markdown创建
+if [ $# != 1 ]
+then
+    echo "missing blogname"
+    echo "usage: go \$blogname"
+    echo "e.g.: go 我的博文"
+    exit 1
+fi
 mydate=$(date +%Y-%m-%d | tr -d "\n") #Assign Output of Shell command to var
 mytime=$(date +%H:%M | tr -d "\n")
 blogname=$(echo -n $1)
diff --git a/bin/og b/bin/og
--- a/bin/og
+++ b/bin/og
@@ -1,3 +1,11 @@
+# update
+if [ $# != 1 ]
+then
+    echo "missing commitlog"
+    echo "usage: og \$commitlog"
+    echo "e.g.: og 我的博文"
+    exit 1
+fi
 git add .
 git commit -m "$1"
 git push origin master
